### ISSUE TITLE
EC-Admin project saveProjects procedure fails when project name has "/"

### ISSUE THREAD

**Issue by smathur-t** [electric-cloud/EC-Admin#127] opened 2018-07-12 16:51 UTC
When I run the EC-Admin->saveProjects procedure in the UI, I get the following error:

Saving Project: ActiveMatrix BusinessWorks Plug-in for Files for Unix/Win 
agent.IDJQXKR3MMW1CHUG.run-88d82845-852d-11e8-b81c-005056affdfc-89092307-852d-11e8-918c-005056affdfc error [NoSuchProject]: Evaluating property '/projects/ActiveMatrix BusinessWorks Plug-in for Files for Unix/Win' in global context 
Project 'ActiveMatrix BusinessWorks Plug-in for Files for Unix' does not exist 
Evaluation failed 
Details: 
Evaluating property '/projects/ActiveMatrix BusinessWorks Plug-in for Files for Unix/Win' in global context 
Project 'ActiveMatrix BusinessWorks Plug-in for Files for Unix' does not exist 
Evaluation failed

This is the code in save Projects step 
#############################################################################
# 
# Copyright 2013 Electric-Cloud Inc. 
# 
#############################################################################
use File::Path;

$[/myProject/scripts/perlHeader] 
$[/myProject/scripts/perlLib] 
# 
# Parameters 
# 
my $path="$[pathname]"; 
my $includeACLs="$[includeACLs]"; 
my $includeNotifiers="$[includeNotifiers]"; 
my $relocatable="$[relocatable]";

my $errorCount=0; 
# Get list of Project 
my ($success, $xPath) = InvokeCommander("SuppressLog", "getProjects");

# Create the directory 
mkpath($path);

my $nodeset = $xPath->find('//project'); 
foreach my $node ($nodeset->get_nodelist) { 
my $pName=$xPath->findvalue('projectName', $node); 
my $pluginName=$xPath->findvalue('pluginName', $node);

# skip plugins 
next if ($pluginName ne ""); 
printf("Saving Project: %s\n", $pName); 
my $filename = $pName; 
$filename =~ tr/\//_/; 
printf("Filename: %s\n", $filename);

my ($success, $xPath, $errMsg, $errCode) = InvokeCommander("SuppressLog", "export", $path."/$filename".".xml", 
{ 'path'=> "/projects/"."$pName", 
'relocatable' => $relocatable, 
'withAcls' => $includeACLs, 
'withNotifiers'=>$includeNotifiers}); 
if (! $success) { 
printf(" Error exporting %s", $pName); 
printf(" %s: %s\n", $errCode, $errMsg); 
$errorCount++; 
} 
} 
exit($errorCount);

**Comment by lrochette** [comment] 2018-07-13 22:41
@smathur-t ,

I checked the code with the latest version v3.1.0 and I can save projects with a slash in the name.
I've added a new test to be sure it does not become a problem in the future

I assume you have an older version of the plugin.
Can you download the latest one please and update your server?

Please let me know if that does not fix your problem.

**Comment by lrochette** [comment] 2018-07-16 14:41
The problem is fixed on Linux but it appears it is still an issue on Windows.
@smathur-t I will work on it more with @vidvijay

**Comment by lrochette** [comment] 2018-07-16 14:58
I have fixed saveAllObjects, not saveProjects (which is kind of obsolete).
I will transform it to call saveAllObjects behind the scenes so we do not lose backward compatibility

**Comment by lrochette** [comment] 2018-08-16 15:47
Fixex

**Closed by lrochette** 2018-08-16 15:47 UTC
Labels: invalid
